[package]
name = "summer-jam"
version = "0.1.0"
edition = "2018"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
derive-new = "0.5"
wasm-bindgen = "0.2"
big-brain = "0.6.0"

# Dependencies for native only.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = { version = "0.5", default-features = false, features = [
    "bevy_wgpu",
    "bevy_winit",
    "render",
    "x11",
] }

# Dependencies for WASM only.
[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { version = "0.5", default-features = false, features = [
    "bevy_winit",
    "render",
] }
bevy_webgl2 = { version = "0.5" }

[patch.crates-io]
bevy_webgl2 = { git = "https://github.com/mrk-its/bevy_webgl2" }
bevy = { git = "https://github.com/bevyengine/bevy" }
winit = { git = "https://github.com/cryscan/winit" }
big-brain = { git = "https://github.com/zkat/big-brain" }
